services:
  dbpg:
    image: postgres:15
    container_name: dbpg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse
    ports:
      - "5433:5432"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - eng-net

  dbt:
    build:
      context: ./dbt_compose/dbt
      dockerfile: Dockerfile
    container_name: dbt
    environment:
      DBT_PROFILES_DIR: /root/.dbt
    volumes:
      - ./dbt_compose/dbt/projeto_dbt_maua:/usr/app
      - ./dbt_compose/dbt/projeto_dbt_maua/profiles.yml:/root/.dbt/profiles.yml    
    working_dir: /usr/app
    command: tail -f /dev/null
    depends_on:
      - dbpg
    networks:
      - eng-net

volumes:
  pgdata:
    driver: local

networks:
  eng-net:
    driver: bridge
