version: 2

models:
  - name: bronze_cliente
    description: "Tabela com os dados brutos dos clientes, carregados diretamente do CSV."
    columns:
      - name: id_cliente
        description: "Identificador único do cliente"
      - name: nome
        description: "Nome completo do cliente"
      - name: email
        description: "Email do cliente"
      - name: telefone
        description: "Telefone informado"
      - name: cpf
        description: "CPF do cliente"
      - name: endereco
        description: "Endereço completo"
      - name: data_cadastro
        description: "Data e hora do cadastro do cliente"

  - name: bronze_compras
    description: "Tabela com os dados brutos de compras realizadas pelos clientes."
    columns:
      - name: id_compra
        description: "Identificador da compra"
      - name: id_cliente
        description: "Chave estrangeira para o cliente"
      - name: id_produto
        description: "Chave estrangeira para o produto"
      - name: data_compra
        description: "Data da compra"

  - name: bronze_produtos
    description: "Tabela com os dados brutos dos produtos disponíveis."
    columns:
      - name: id_produto
        description: "Identificador único do produto"
      - name: nome
        description: "Nome do produto"
      - name: preco
        description: "Preço unitário do produto"

  - name: silver_cliente
    description: "Tabela tratada dos clientes, com remoção de dados sensíveis e transformação da data."
    columns:
      - name: id_cliente
        description: "Identificador único do cliente"
      - name: nome
        description: "Nome do cliente"
      - name: email
        description: "Email do cliente"
      - name: data_cadastro
        description: "Data (sem hora) do cadastro do cliente"

  - name: gold_comportamento_cliente
    description: "Agregações sobre comportamento de compra por cliente: total de compras, gasto total e produto mais comprado."
    columns:
      - name: id_cliente
        description: "Identificador do cliente"
      - name: total_compras
        description: "Número total de compras realizadas pelo cliente"
      - name: valor_total_gasto
        description: "Soma total gasta pelo cliente"
      - name: produto_mais_comprado
        description: "Produto mais comprado pelo cliente"
