name: eng_dados_maua
version: '1.0'
config-version: 2

profile: eng_dados_maua

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
analysis-paths: ["analyses"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  eng_dados_maua:
    bronze:
      materialized: view
    silver:
      materialized: view
    gold:
      materialized: table
