# projeto_dbt:
#   target: dev
#   outputs:
#     dev:
#       type: postgres
#       host: "{{ env_var('DB_HOST') }}"
#       user: "{{ env_var('DB_USER') }}"
#       password: "{{ env_var('DB_PASSWORD') }}"
#       port: "{{ env_var('DB_PORT') | int }}"
#       dbname: "{{ env_var('DB_NAME') }}"
#       schema: "{{ env_var('DB_SCHEMA') }}"
#       threads: 1
#       keepalives_idle: 0

eng_dados_maua:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db  # nome do container PostgreSQL no docker-compose
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: public
      threads: 1
