version: '3.8'

services:
  dbpg:
    image: postgres:15
    container_name: dbpg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: warehouse
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # Executa o SQL no primeiro start

volumes:
  pgdata:
    driver: local